"""Add password fields to patient

Revision ID: abf6ce69e81a
Revises: 9bfae6a81f34
Create Date: 2025-11-25 18:21:13.063650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf6ce69e81a'
down_revision = '9bfae6a81f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('first_access', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('first_access')
        batch_op.drop_column('senha')

    # ### end Alembic commands ###
